import React, { useState } from 'react';
import { useVision } from '../context/VisionContext';

export const InitialTeaching: React.FC = () => {
  const {
    session,
    teachingAction,
    resourceSelection,
    beginPractice,
    loading
  } = useVision();

  const [pedagogyOpen, setPedagogyOpen] = useState<boolean>(false);

  if (!session) return null;

  const targetConcept = session.target_concept || 'Target Concept';
  const subject = session.subject || 'Domain';
  const learnerLevel = session.learner_level || 'Adaptive';
  const learningGoal = session.learning_goal || 'Understand';

  const explanation = teachingAction?.explanation || 'Lesson explanation is being generated by the Tutor Agent...';
  const keyTakeaways = teachingAction?.key_takeaways || [];
  const codeExample = teachingAction?.code_example;
  const teachingMode = teachingAction?.teaching_mode || 'Adaptive Concept Synthesis';
  const pedagogyRationale = teachingAction?.pedagogy_rationale;

  const handleStartPractice = async () => {
    await beginPractice(false);
  };

  return (
    <div className="flex flex-col w-full gap-6 max-w-4xl mx-auto">
      {/* Tutor Presence & Dynamic Synthesis Banner */}
      <div className="rounded-xl bg-[#0B111E]/95 border border-[#00D2FF]/20 p-5 sm:p-6 shadow-xl relative overflow-hidden backdrop-blur-md">
        <div className="absolute -right-16 -top-16 w-64 h-64 bg-[#00D2FF]/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -left-12 -bottom-12 w-48 h-48 bg-[#10B981]/10 rounded-full blur-2xl pointer-events-none" />

        <div className="relative z-10 flex flex-col gap-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2.5">
              <div className="px-2.5 py-1 rounded bg-[#00D2FF]/15 border border-[#00D2FF]/40 text-[#00D2FF] font-mono text-xs uppercase tracking-wider flex items-center gap-1.5 shadow-[0_0_12px_rgba(0,210,255,0.2)]">
                <span className="w-2 h-2 rounded-full bg-[#00D2FF] animate-ping" />
                VISION TUTOR AGENT
              </div>
              <span className="text-xs text-[#DFE8F2]">
                Personalized for <strong className="text-[#10B981] font-mono">{learnerLevel}</strong> level · Goal: <strong className="text-[#F59E0B] font-mono">{learningGoal}</strong>
              </span>
            </div>

            <div className="px-2.5 py-1 rounded bg-[#141F36] border border-[#1F2F4A] text-sky-200 font-mono text-xs flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm text-[#00D2FF]">hub</span>
              <span>Mode: <strong className="text-[#00D2FF]">{teachingMode}</strong></span>
            </div>
          </div>

          {/* Expandable Pedagogy Rationale */}
          <div className="bg-[#0E1526]/80 border border-[#1F2F4A] rounded-lg p-3 backdrop-blur-sm transition-all hover:border-[#00D2FF]/40">
            <button
              onClick={() => setPedagogyOpen(!pedagogyOpen)}
              className="flex items-center justify-between w-full text-left text-xs font-mono"
            >
              <div className="flex items-center gap-2 text-[#00D2FF]">
                <span className="material-symbols-outlined text-sm">psychology_alt</span>
                <span className="font-semibold">Why am I learning this this way?</span>
                <span className="text-[10px] uppercase px-1.5 py-0.2 rounded bg-sky-500/20 text-sky-300 border border-sky-400/30">
                  Pedagogical Rationale
                </span>
              </div>
              <span className="material-symbols-outlined text-sm text-sky-300">
                {pedagogyOpen ? 'expand_less' : 'expand_more'}
              </span>
            </button>

            {pedagogyOpen && (
              <div className="mt-2.5 pt-2.5 border-t border-[#1F2F4A] text-xs text-[#8EA4B8] leading-relaxed">
                {pedagogyRationale ||
                  `Tutor Agent calibrated the mental model for ${learnerLevel} level. It optimizes retention by establishing structural invariants before code syntax execution.`}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Lesson Header */}
      <div className="flex flex-col gap-1.5">
        <div className="flex items-center gap-2 text-xs font-mono text-sky-400 uppercase tracking-wider">
          <span className="w-1.5 h-1.5 rounded-full bg-[#00D2FF]" />
          <span>Foundational Synthesis</span>
          <span className="text-[#64748B]">·</span>
          <span className="text-[#8EA4B8]">{subject}</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-white">
          {targetConcept}
        </h1>
      </div>

      {/* Main Explanation */}
      <div className="rounded-xl bg-[#0E1526]/90 border border-[#1F2F4A] p-6 shadow-xl flex flex-col gap-5 text-sm leading-relaxed text-[#DFE8F2]">
        <div className="prose prose-invert max-w-none whitespace-pre-line text-base text-[#DFE8F2]/90 leading-relaxed font-normal">
          {explanation}
        </div>

        {/* Code Example if present */}
        {codeExample && (
          <div className="flex flex-col gap-2 rounded-lg bg-[#06080F] border border-[#1F2F4A] p-4 font-mono text-xs overflow-x-auto">
            <div className="flex items-center justify-between text-[#8EA4B8] text-[11px] pb-2 border-b border-[#1F2F4A]">
              <span className="uppercase tracking-wider">Illustrative Code Implementation</span>
              <span className="text-sky-400">Tutor Verified</span>
            </div>
            <pre className="text-sky-200 mt-2 whitespace-pre leading-5">
              <code>{codeExample}</code>
            </pre>
          </div>
        )}

        {/* Key Takeaways */}
        {keyTakeaways.length > 0 && (
          <div className="flex flex-col gap-2.5 p-4 rounded-xl bg-[#0A101D] border border-[#1F2F4A]">
            <span className="text-xs font-mono font-semibold uppercase tracking-wider text-[#10B981] flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm">checklist</span>
              Key Conceptual Takeaways
            </span>
            <ul className="flex flex-col gap-1.5 text-xs text-[#DFE8F2]">
              {keyTakeaways.map((takeaway, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-[#00D2FF] font-mono mt-0.5">•</span>
                  <span>{takeaway}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Recommended Resources from Resource Agent */}
        {resourceSelection && resourceSelection.recommended_links && resourceSelection.recommended_links.length > 0 && (
          <div className="flex flex-col gap-2 pt-2 border-t border-[#1F2F4A]">
            <span className="text-xs font-mono text-[#8EA4B8] flex items-center gap-1.5 uppercase tracking-wider">
              <span className="material-symbols-outlined text-sm text-[#F59E0B]">library_books</span>
              Recommended Learning Resources
            </span>
            <div className="flex flex-wrap gap-2">
              {resourceSelection.recommended_links.map((link, idx) => {
                const title = typeof link === 'string' ? link : link.title || link.url || 'Resource Link';
                const url = typeof link === 'string' ? link : link.url || '#';
                return (
                  <a
                    key={idx}
                    href={url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-3 py-1.5 rounded-lg bg-[#0A101D] border border-[#1F2F4A] hover:border-[#00D2FF] text-xs font-mono text-sky-300 hover:text-white transition-all flex items-center gap-1.5"
                  >
                    <span className="material-symbols-outlined text-xs">open_in_new</span>
                    <span>{title}</span>
                  </a>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* Primary Action: I'm Ready — Start Practice */}
      <div className="p-5 rounded-xl bg-[#0B111E] border border-[#00D2FF]/30 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-2xl">
        <div className="flex flex-col">
          <span className="text-sm font-semibold text-white">Understood the concept?</span>
          <span className="text-xs text-[#8EA4B8]">
            Proceed to the adaptive practice task designed by the Exercise Agent.
          </span>
        </div>

        <button
          onClick={handleStartPractice}
          disabled={loading}
          className="w-full sm:w-auto px-7 py-3.5 rounded-xl bg-[#00D2FF] hover:bg-cyan-400 text-slate-950 font-mono font-bold text-sm transition-all shadow-[0_0_20px_rgba(0,210,255,0.4)] disabled:opacity-50 flex items-center justify-center gap-2"
        >
          {loading ? (
            <>
              <span className="material-symbols-outlined text-base animate-spin">sync</span>
              <span>Transitioning to Practice...</span>
            </>
          ) : (
            <>
              <span>I'm Ready — Start Practice</span>
              <span className="material-symbols-outlined text-base">arrow_forward</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
};
