import React, { useState } from 'react';
import { useVision } from '../context/VisionContext';

export const InitialTeaching: React.FC = () => {
  const {
    session,
    teachingAction,
    resourceSelection,
    beginPractice,
    loading
  } = useVision();

  const [pedagogyOpen, setPedagogyOpen] = useState<boolean>(false);
  const [hintLevel, setHintLevel] = useState<number>(0);
  const [userReflection, setUserReflection] = useState<string>('');
  const [reflectionSubmitted, setReflectionSubmitted] = useState<boolean>(false);

  if (!session) return null;

  const targetConcept = session.target_concept || 'Target Concept';
  const subject = session.subject || 'Domain';
  const learnerLevel = session.learner_level || 'Adaptive';
  const learningGoal = session.learning_goal || 'Understand';

  const explanation = teachingAction?.explanation || teachingAction?.explanation_text || 'Lesson explanation is being generated by the Tutor Agent...';
  const keyTakeaways = teachingAction?.key_takeaways || [];
  const codeExample = teachingAction?.code_example;
  const teachingMode = teachingAction?.teaching_mode || teachingAction?.teaching_strategy || 'Adaptive Concept Synthesis';
  const pedagogyRationale = teachingAction?.pedagogy_rationale;

  const workedExample = teachingAction?.worked_example;
  const fadedExample = teachingAction?.faded_example;
  const misconceptionContrast = teachingAction?.misconception_contrast;
  const hintLadder = teachingAction?.hint_ladder || [];
  const selfExplanationPrompt = teachingAction?.self_explanation_prompt;
  const learningObjectives = teachingAction?.learning_objectives || [];

  const handleStartPractice = async () => {
    await beginPractice(false);
  };

  return (
    <div className="flex flex-col w-full gap-6 max-w-4xl mx-auto">
      {/* Tutor Presence & Dynamic Synthesis Banner */}
      <div className="rounded-xl bg-[#0B111E]/95 border border-[#00D2FF]/20 p-5 sm:p-6 shadow-xl relative overflow-hidden backdrop-blur-md">
        <div className="absolute -right-16 -top-16 w-64 h-64 bg-[#00D2FF]/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -left-12 -bottom-12 w-48 h-48 bg-[#10B981]/10 rounded-full blur-2xl pointer-events-none" />

        <div className="relative z-10 flex flex-col gap-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2.5">
              <div className="px-2.5 py-1 rounded bg-[#00D2FF]/15 border border-[#00D2FF]/40 text-[#00D2FF] font-mono text-xs uppercase tracking-wider flex items-center gap-1.5 shadow-[0_0_12px_rgba(0,210,255,0.2)]">
                <span className="w-2 h-2 rounded-full bg-[#00D2FF] animate-ping" />
                VISION TUTOR AGENT
              </div>
              <span className="text-xs text-[#DFE8F2]">
                Personalized for <strong className="text-[#10B981] font-mono">{learnerLevel}</strong> level · Goal: <strong className="text-[#F59E0B] font-mono">{learningGoal}</strong>
              </span>
            </div>

            <div className="px-2.5 py-1 rounded bg-[#141F36] border border-[#1F2F4A] text-sky-200 font-mono text-xs flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm text-[#00D2FF]">hub</span>
              <span>Mode: <strong className="text-[#00D2FF]">{teachingMode}</strong></span>
            </div>
          </div>

          {/* Expandable Pedagogy Rationale */}
          <div className="bg-[#0E1526]/80 border border-[#1F2F4A] rounded-lg p-3 backdrop-blur-sm transition-all hover:border-[#00D2FF]/40">
            <button
              onClick={() => setPedagogyOpen(!pedagogyOpen)}
              className="flex items-center justify-between w-full text-left text-xs font-mono"
            >
              <div className="flex items-center gap-2 text-[#00D2FF]">
                <span className="material-symbols-outlined text-sm">psychology_alt</span>
                <span className="font-semibold">Why am I learning this this way?</span>
                <span className="text-[10px] uppercase px-1.5 py-0.2 rounded bg-sky-500/20 text-sky-300 border border-sky-400/30">
                  Pedagogical Rationale
                </span>
              </div>
              <span className="material-symbols-outlined text-sm text-sky-300">
                {pedagogyOpen ? 'expand_less' : 'expand_more'}
              </span>
            </button>

            {pedagogyOpen && (
              <div className="mt-2.5 pt-2.5 border-t border-[#1F2F4A] text-xs text-[#8EA4B8] leading-relaxed">
                {pedagogyRationale ||
                  `Tutor Agent calibrated the mental model for ${learnerLevel} level. It optimizes retention by establishing structural invariants before code syntax execution.`}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Lesson Header */}
      <div className="flex flex-col gap-1.5">
        <div className="flex items-center gap-2 text-xs font-mono text-sky-400 uppercase tracking-wider">
          <span className="w-1.5 h-1.5 rounded-full bg-[#00D2FF]" />
          <span>Foundational Synthesis</span>
          <span className="text-[#64748B]">·</span>
          <span className="text-[#8EA4B8]">{subject}</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-white">
          {targetConcept}
        </h1>
      </div>

      {/* Structured Learning Objectives */}
      {learningObjectives.length > 0 && (
        <div className="p-4 rounded-xl bg-[#0A101D] border border-[#1F2F4A] flex flex-col gap-2.5">
          <span className="text-xs font-mono text-sky-300 uppercase tracking-wider flex items-center gap-1.5">
            <span className="material-symbols-outlined text-sm text-[#00D2FF]">target</span>
            Calibrated Learning Objectives
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {learningObjectives.map((obj, i) => (
              <div key={i} className="p-2.5 rounded-lg bg-[#06080F] border border-[#1F2F4A] text-xs text-[#DFE8F2] flex items-start gap-2">
                <span className="px-1.5 py-0.5 rounded bg-sky-500/20 text-[#00D2FF] font-mono text-[10px] uppercase">
                  {obj.objective_type}
                </span>
                <span className="leading-snug">{obj.objective}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Main Explanation Card */}
      <div className="rounded-xl bg-[#0E1526]/90 border border-[#1F2F4A] p-6 shadow-xl flex flex-col gap-6 text-sm leading-relaxed text-[#DFE8F2]">
        <div className="prose prose-invert max-w-none whitespace-pre-line text-base text-[#DFE8F2]/90 leading-relaxed font-normal">
          {explanation}
        </div>

        {/* Misconception Contrast Warning */}
        {misconceptionContrast && (
          <div className="flex flex-col gap-3 p-4 rounded-xl bg-amber-950/20 border border-amber-500/30">
            <div className="flex items-center gap-2 text-amber-400 font-mono text-xs uppercase font-bold tracking-wider">
              <span className="material-symbols-outlined text-sm">warning</span>
              Conceptual Distinction & Common Pitfalls
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
              <div className="p-3 rounded-lg bg-[#06080F] border border-emerald-500/30 flex flex-col gap-1">
                <span className="text-emerald-400 font-mono font-semibold">✓ Correct Mental Model</span>
                <p className="text-[#DFE8F2]">{misconceptionContrast.correct_model}</p>
              </div>
              <div className="p-3 rounded-lg bg-[#06080F] border border-rose-500/30 flex flex-col gap-1">
                <span className="text-rose-400 font-mono font-semibold">✕ Common Misconception</span>
                <p className="text-[#DFE8F2]">{misconceptionContrast.mistaken_model}</p>
              </div>
            </div>
            <p className="text-xs text-amber-200/90 font-mono">
              <strong>Key Rule:</strong> {misconceptionContrast.key_distinction}
            </p>
          </div>
        )}

        {/* Step-by-Step Worked Example */}
        {workedExample && (
          <div className="flex flex-col gap-3 p-4 rounded-xl bg-[#06080F] border border-[#00D2FF]/30">
            <div className="flex items-center justify-between text-xs font-mono border-b border-[#1F2F4A] pb-2">
              <span className="text-[#00D2FF] font-semibold uppercase tracking-wider flex items-center gap-1.5">
                <span className="material-symbols-outlined text-sm">model_training</span>
                Modeled Step-by-Step Example
              </span>
              <span className="text-slate-400">Scaffold Level: Low</span>
            </div>
            <div className="text-xs text-sky-200">
              <strong>Scenario:</strong> {workedExample.problem}
            </div>
            <div className="flex flex-col gap-2">
              {workedExample.steps.map((step, idx) => (
                <div key={idx} className="flex items-start gap-2.5 p-2 rounded bg-[#0E1526] border border-[#1F2F4A] text-xs">
                  <span className="px-2 py-0.5 rounded bg-[#00D2FF]/20 text-[#00D2FF] font-mono font-bold text-[11px]">
                    Step {step.step_number}
                  </span>
                  <div className="flex flex-col gap-0.5">
                    <span className="text-white font-medium">{step.action}</span>
                    <span className="text-slate-400 text-[11px] italic">Reason: {step.reason}</span>
                  </div>
                </div>
              ))}
            </div>
            <div className="text-xs text-emerald-300 font-mono pt-1">
              <strong>Outcome:</strong> {workedExample.result} — {workedExample.why_this_works}
            </div>
          </div>
        )}

        {/* Faded Example (Partially Worked) */}
        {fadedExample && (
          <div className="flex flex-col gap-3 p-4 rounded-xl bg-[#0A101D] border border-indigo-500/30">
            <div className="flex items-center gap-2 text-indigo-300 font-mono text-xs uppercase font-bold tracking-wider">
              <span className="material-symbols-outlined text-sm">incomplete_circle</span>
              Guided Faded Exercise
            </div>
            <p className="text-xs text-[#DFE8F2]">{fadedExample.problem}</p>
            <div className="p-3 rounded-lg bg-[#06080F] border border-indigo-500/20 text-xs text-indigo-200 flex flex-col gap-1.5">
              <span className="font-semibold text-white">Your Turn:</span>
              <p>{fadedExample.faded_step.prompt}</p>
              <span className="text-[11px] text-indigo-400 italic">Hint: {fadedExample.faded_step.scaffold_hint}</span>
            </div>
          </div>
        )}

        {/* Code Example if present */}
        {codeExample && (
          <div className="flex flex-col gap-2 rounded-lg bg-[#06080F] border border-[#1F2F4A] p-4 font-mono text-xs overflow-x-auto">
            <div className="flex items-center justify-between text-[#8EA4B8] text-[11px] pb-2 border-b border-[#1F2F4A]">
              <span className="uppercase tracking-wider">Illustrative Code Implementation</span>
              <span className="text-sky-400">Tutor Verified</span>
            </div>
            <pre className="text-sky-200 mt-2 whitespace-pre leading-5">
              <code>{codeExample}</code>
            </pre>
          </div>
        )}

        {/* Self Explanation / Active Reflection Prompt */}
        {selfExplanationPrompt && (
          <div className="flex flex-col gap-3 p-4 rounded-xl bg-[#081224] border border-teal-500/30">
            <span className="text-xs font-mono font-semibold uppercase tracking-wider text-teal-300 flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm">draw</span>
              Active Self-Explanation Check
            </span>
            <p className="text-xs text-[#DFE8F2] leading-relaxed">{selfExplanationPrompt}</p>
            {!reflectionSubmitted ? (
              <div className="flex flex-col gap-2">
                <textarea
                  value={userReflection}
                  onChange={(e) => setUserReflection(e.target.value)}
                  placeholder="Type your explanation here to calibrate your mental model..."
                  rows={2}
                  className="w-full rounded-lg bg-[#06080F] border border-[#1F2F4A] p-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-teal-400 font-sans"
                />
                <button
                  onClick={() => userReflection.trim() && setReflectionSubmitted(true)}
                  disabled={!userReflection.trim()}
                  className="self-end px-3 py-1.5 rounded bg-teal-600/80 hover:bg-teal-500 text-white font-mono text-xs disabled:opacity-40 transition-colors"
                >
                  Verify Explanation
                </button>
              </div>
            ) : (
              <div className="p-3 rounded-lg bg-teal-950/40 border border-teal-500/40 text-xs text-teal-200 flex items-center gap-2">
                <span className="material-symbols-outlined text-sm text-teal-400">check_circle</span>
                <span>Active recall recorded. This strengthens neural consolidation for the upcoming practice!</span>
              </div>
            )}
          </div>
        )}

        {/* 5-Level Hint Ladder Preview */}
        {hintLadder.length > 0 && (
          <div className="flex flex-col gap-2.5 p-4 rounded-xl bg-[#06080F] border border-[#1F2F4A]">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono uppercase text-sky-400 flex items-center gap-1.5">
                <span className="material-symbols-outlined text-sm">lightbulb</span>
                Scaffolded Hint Ladder ({hintLadder.length} Levels Available)
              </span>
              <button
                onClick={() => setHintLevel(prev => (prev < hintLadder.length ? prev + 1 : 0))}
                className="text-[11px] font-mono text-sky-300 hover:text-white px-2 py-1 rounded bg-[#141F36] border border-[#1F2F4A]"
              >
                {hintLevel === 0 ? 'Preview Hint 1' : hintLevel < hintLadder.length ? `Reveal Hint ${hintLevel + 1}` : 'Collapse Hints'}
              </button>
            </div>
            {hintLevel > 0 && (
              <div className="flex flex-col gap-2 mt-2">
                {hintLadder.slice(0, hintLevel).map((h, idx) => (
                  <div key={idx} className="p-2.5 rounded bg-[#0E1526] border border-[#1F2F4A] text-xs flex items-start gap-2">
                    <span className="px-1.5 py-0.5 rounded bg-sky-500/20 text-[#00D2FF] font-mono text-[10px]">
                      {h.label}
                    </span>
                    <span className="text-[#DFE8F2]">{h.text}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Key Takeaways */}
        {keyTakeaways.length > 0 && (
          <div className="flex flex-col gap-2.5 p-4 rounded-xl bg-[#0A101D] border border-[#1F2F4A]">
            <span className="text-xs font-mono font-semibold uppercase tracking-wider text-[#10B981] flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm">checklist</span>
              Key Conceptual Takeaways
            </span>
            <ul className="flex flex-col gap-1.5 text-xs text-[#DFE8F2]">
              {keyTakeaways.map((takeaway, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-[#00D2FF] font-mono mt-0.5">•</span>
                  <span>{takeaway}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Recommended Resources from Resource Agent */}
        {resourceSelection && resourceSelection.recommended_links && resourceSelection.recommended_links.length > 0 && (
          <div className="flex flex-col gap-2 pt-2 border-t border-[#1F2F4A]">
            <span className="text-xs font-mono text-[#8EA4B8] flex items-center gap-1.5 uppercase tracking-wider">
              <span className="material-symbols-outlined text-sm text-[#F59E0B]">library_books</span>
              Recommended Learning Resources
            </span>
            <div className="flex flex-wrap gap-2">
              {resourceSelection.recommended_links.map((link, idx) => {
                const title = typeof link === 'string' ? link : link.title || link.url || 'Resource Link';
                const url = typeof link === 'string' ? link : link.url || '#';
                return (
                  <a
                    key={idx}
                    href={url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-3 py-1.5 rounded-lg bg-[#0A101D] border border-[#1F2F4A] hover:border-[#00D2FF] text-xs font-mono text-sky-300 hover:text-white transition-all flex items-center gap-1.5"
                  >
                    <span className="material-symbols-outlined text-xs">open_in_new</span>
                    <span>{title}</span>
                  </a>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* Primary Action: I'm Ready — Start Practice */}
      <div className="p-5 rounded-xl bg-[#0B111E] border border-[#00D2FF]/30 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-2xl">
        <div className="flex flex-col">
          <span className="text-sm font-semibold text-white">Understood the concept?</span>
          <span className="text-xs text-[#8EA4B8]">
            Proceed to the adaptive practice task designed by the Exercise Agent.
          </span>
        </div>

        <button
          onClick={handleStartPractice}
          disabled={loading}
          className="w-full sm:w-auto px-7 py-3.5 rounded-xl bg-[#00D2FF] hover:bg-cyan-400 text-slate-950 font-mono font-bold text-sm transition-all shadow-[0_0_20px_rgba(0,210,255,0.4)] disabled:opacity-50 flex items-center justify-center gap-2"
        >
          {loading ? (
            <>
              <span className="material-symbols-outlined text-base animate-spin">sync</span>
              <span>Transitioning to Practice...</span>
            </>
          ) : (
            <>
              <span>I'm Ready — Start Practice</span>
              <span className="material-symbols-outlined text-base">arrow_forward</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
};
