import React, { useState } from 'react';
import { useVision } from '../context/VisionContext';

export const InitialTeaching: React.FC = () => {
  const {
    session,
    teachingAction,
    resourceSelection,
    beginPractice,
    loading
  } = useVision();

  const [pedagogyOpen, setPedagogyOpen] = useState<boolean>(false);
  const [hintLevel, setHintLevel] = useState<number>(0);
  const [userReflection, setUserReflection] = useState<string>('');
  const [reflectionSubmitted, setReflectionSubmitted] = useState<boolean>(false);
  const [copiedCode, setCopiedCode] = useState<boolean>(false);

  if (!session) return null;

  const targetConcept = session.target_concept || 'Target Concept';
  const subject = session.subject || 'Domain';
  const learnerLevel = session.learner_level || 'Adaptive';
  const learningGoal = session.learning_goal || 'Understand';

  const definition = teachingAction?.definition || teachingAction?.explanation || 'Lesson definition is being generated by the Tutor Agent...';
  const examples = teachingAction?.examples || [];
  const pythonCode = teachingAction?.pseudocode_python || teachingAction?.code_example || '';
  const keyTakeaways = teachingAction?.key_takeaways || [];
  const teachingMode = teachingAction?.teaching_mode || teachingAction?.teaching_strategy || 'Dynamic Concept Synthesis';
  const pedagogyRationale = teachingAction?.pedagogy_rationale;

  const workedExample = teachingAction?.worked_example;
  const fadedExample = teachingAction?.faded_example;
  const misconceptionContrast = teachingAction?.misconception_contrast;
  const hintLadder = teachingAction?.hint_ladder || [];
  const selfExplanationPrompt = teachingAction?.self_explanation_prompt;
  const learningObjectives = teachingAction?.learning_objectives || [];

  const handleCopyCode = () => {
    if (pythonCode) {
      navigator.clipboard.writeText(pythonCode);
      setCopiedCode(true);
      setTimeout(() => setCopiedCode(false), 2000);
    }
  };

  const handleStartPractice = async () => {
    await beginPractice(false);
  };

  return (
    <div className="flex flex-col w-full gap-6 max-w-4xl mx-auto">
      {/* Dynamic Tutor Banner */}
      <div className="rounded-xl bg-[#0B111E]/95 border border-[#00D2FF]/30 p-5 sm:p-6 shadow-xl relative overflow-hidden backdrop-blur-md">
        <div className="absolute -right-16 -top-16 w-64 h-64 bg-[#00D2FF]/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -left-12 -bottom-12 w-48 h-48 bg-[#10B981]/10 rounded-full blur-2xl pointer-events-none" />

        <div className="relative z-10 flex flex-col gap-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2.5">
              <div className="px-2.5 py-1 rounded bg-[#00D2FF]/15 border border-[#00D2FF]/40 text-[#00D2FF] font-mono text-xs uppercase tracking-wider flex items-center gap-1.5 shadow-[0_0_12px_rgba(0,210,255,0.2)]">
                <span className="w-2 h-2 rounded-full bg-[#00D2FF] animate-ping" />
                VISION DYNAMIC TUTOR AGENT
              </div>
              <span className="text-xs text-[#DFE8F2]">
                Personalized for <strong className="text-[#10B981] font-mono">{learnerLevel}</strong> level · Goal: <strong className="text-[#F59E0B] font-mono">{learningGoal}</strong>
              </span>
            </div>

            <div className="px-2.5 py-1 rounded bg-[#141F36] border border-[#1F2F4A] text-sky-200 font-mono text-xs flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm text-[#00D2FF]">school</span>
              <span>Subject: <strong className="text-[#00D2FF]">{subject}</strong></span>
            </div>
          </div>

          {/* Expandable Pedagogy Rationale */}
          <div className="bg-[#0E1526]/80 border border-[#1F2F4A] rounded-lg p-3 backdrop-blur-sm transition-all hover:border-[#00D2FF]/40">
            <button
              onClick={() => setPedagogyOpen(!pedagogyOpen)}
              className="flex items-center justify-between w-full text-left text-xs font-mono"
            >
              <div className="flex items-center gap-2 text-[#00D2FF]">
                <span className="material-symbols-outlined text-sm">psychology_alt</span>
                <span className="font-semibold">Pedagogical Calibration</span>
                <span className="text-[10px] uppercase px-1.5 py-0.2 rounded bg-sky-500/20 text-sky-300 border border-sky-400/30">
                  Prerequisite-Aware Instruction
                </span>
              </div>
              <span className="material-symbols-outlined text-sm text-sky-300">
                {pedagogyOpen ? 'expand_less' : 'expand_more'}
              </span>
            </button>

            {pedagogyOpen && (
              <div className="mt-2.5 pt-2.5 border-t border-[#1F2F4A] text-xs text-[#8EA4B8] leading-relaxed">
                {pedagogyRationale ||
                  `The Dynamic Tutor Agent structured this lesson strictly according to your confirmed prerequisite foundation. The lesson provides: 1) Definition, 2) Step-by-step Examples, and 3) Python Pseudocode.`}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Lesson Header */}
      <div className="flex flex-col gap-1.5">
        <div className="flex items-center gap-2 text-xs font-mono text-sky-400 uppercase tracking-wider">
          <span className="w-1.5 h-1.5 rounded-full bg-[#00D2FF]" />
          <span>Core Concept Mastery</span>
          <span className="text-[#64748B]">·</span>
          <span className="text-[#8EA4B8]">{subject}</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-white">
          {targetConcept}
        </h1>
      </div>

      {/* Structured Learning Objectives */}
      {learningObjectives.length > 0 && (
        <div className="p-4 rounded-xl bg-[#0A101D] border border-[#1F2F4A] flex flex-col gap-2.5">
          <span className="text-xs font-mono text-sky-300 uppercase tracking-wider flex items-center gap-1.5">
            <span className="material-symbols-outlined text-sm text-[#00D2FF]">target</span>
            Target Learning Objectives
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {learningObjectives.map((obj, i) => (
              <div key={i} className="p-2.5 rounded-lg bg-[#06080F] border border-[#1F2F4A] text-xs text-[#DFE8F2] flex items-start gap-2">
                <span className="px-1.5 py-0.5 rounded bg-sky-500/20 text-[#00D2FF] font-mono text-[10px] uppercase">
                  {obj.objective_type || 'Core'}
                </span>
                <span className="leading-snug">{obj.objective}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* 1. THE DEFINITION OF THE CONCEPT */}
      {/* ========================================================================= */}
      <div className="rounded-2xl bg-[#0E1526]/95 border border-[#1F2F4A] p-6 sm:p-7 shadow-xl flex flex-col gap-4 text-[#DFE8F2]">
        <div className="flex items-center justify-between border-b border-[#1F2F4A] pb-3">
          <div className="flex items-center gap-2 text-sm font-mono font-bold text-white uppercase tracking-wider">
            <span className="flex items-center justify-center w-6 h-6 rounded-md bg-[#00D2FF]/20 text-[#00D2FF] text-xs font-black">
              1
            </span>
            <span>Concept Definition & Mental Model</span>
          </div>
          <span className="text-xs font-mono text-[#00D2FF] px-2 py-0.5 rounded bg-[#00D2FF]/10 border border-[#00D2FF]/20">
            Core Foundation
          </span>
        </div>

        <div className="prose prose-invert max-w-none whitespace-pre-line text-sm sm:text-base text-[#DFE8F2] leading-relaxed font-normal">
          {definition}
        </div>
      </div>

      {/* ========================================================================= */}
      {/* 2. THE EXAMPLES OF THE CONCEPT (2-3 Step-by-Step Examples) */}
      {/* ========================================================================= */}
      <div className="rounded-2xl bg-[#0E1526]/95 border border-[#1F2F4A] p-6 sm:p-7 shadow-xl flex flex-col gap-5 text-[#DFE8F2]">
        <div className="flex items-center justify-between border-b border-[#1F2F4A] pb-3">
          <div className="flex items-center gap-2 text-sm font-mono font-bold text-white uppercase tracking-wider">
            <span className="flex items-center justify-center w-6 h-6 rounded-md bg-[#10B981]/20 text-[#10B981] text-xs font-black">
              2
            </span>
            <span>Practical Step-by-Step Examples</span>
          </div>
          <span className="text-xs font-mono text-[#10B981] px-2 py-0.5 rounded bg-[#10B981]/10 border border-[#10B981]/20">
            {examples.length > 0 ? `${examples.length} Worked Scenarios` : 'Step-by-Step Walkthrough'}
          </span>
        </div>

        {examples.length > 0 ? (
          <div className="flex flex-col gap-4">
            {examples.map((ex, idx) => (
              <div
                key={idx}
                className="flex flex-col gap-3 p-4 sm:p-5 rounded-xl bg-[#06080F] border border-[#1F2F4A] hover:border-[#00D2FF]/40 transition-colors"
              >
                {/* Example Header */}
                <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#1F2F4A]/70 pb-2.5">
                  <span className="text-sm font-semibold text-white flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded bg-[#00D2FF]/15 text-[#00D2FF] font-mono text-xs font-bold">
                      Example {idx + 1}
                    </span>
                    <span>{ex.title}</span>
                  </span>
                  <span className="text-xs font-mono text-slate-400">Step Trace</span>
                </div>

                {/* Scenario Description */}
                <div className="text-xs sm:text-sm text-slate-300">
                  <strong className="text-white font-mono">Scenario: </strong>
                  {ex.scenario}
                </div>

                {/* Step Trace Pills */}
                {ex.steps && ex.steps.length > 0 && (
                  <div className="flex flex-col gap-2 mt-1">
                    {ex.steps.map((step, sIdx) => (
                      <div
                        key={sIdx}
                        className="flex items-start gap-3 p-3 rounded-lg bg-[#0E1526] border border-[#1F2F4A] text-xs"
                      >
                        <span className="px-2 py-0.5 rounded bg-[#00D2FF]/20 text-[#00D2FF] font-mono font-bold text-[11px] shrink-0 mt-0.5">
                          Step {step.step_number || sIdx + 1}
                        </span>
                        <div className="flex flex-col gap-1 w-full">
                          <span className="text-white font-medium">{step.action}</span>
                          {step.reason && (
                            <span className="text-slate-400 text-[11px] italic">
                              Why: {step.reason}
                            </span>
                          )}
                          {step.state_transition && (
                            <span className="text-[#00D2FF] font-mono text-[11px] bg-[#06080F] px-2 py-1 rounded border border-[#1F2F4A] mt-0.5">
                              State: {step.state_transition}
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}

                {/* Visual / ASCII diagram if available */}
                {ex.visual_or_output && (
                  <div className="p-3 rounded-lg bg-[#0A0F1D] border border-cyan-500/20 font-mono text-xs text-cyan-300 overflow-x-auto whitespace-pre">
                    <div className="text-[10px] text-slate-400 uppercase tracking-wider mb-1 font-sans font-bold">
                      Visual / State Diagram:
                    </div>
                    {ex.visual_or_output}
                  </div>
                )}

                {/* Result & Explanation */}
                <div className="flex flex-col gap-1 pt-1 text-xs">
                  <div className="text-emerald-300 font-mono">
                    <strong>Result:</strong> {ex.result}
                  </div>
                  {ex.explanation && (
                    <div className="text-slate-300 italic">
                      <strong>Principle:</strong> {ex.explanation}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        ) : workedExample ? (
          /* Backward compatibility fallback to single worked example */
          <div className="flex flex-col gap-3 p-4 rounded-xl bg-[#06080F] border border-[#00D2FF]/30">
            <div className="text-xs text-sky-200">
              <strong>Scenario:</strong> {workedExample.problem}
            </div>
            <div className="flex flex-col gap-2">
              {workedExample.steps.map((step, idx) => (
                <div key={idx} className="flex items-start gap-2.5 p-2 rounded bg-[#0E1526] border border-[#1F2F4A] text-xs">
                  <span className="px-2 py-0.5 rounded bg-[#00D2FF]/20 text-[#00D2FF] font-mono font-bold text-[11px]">
                    Step {step.step_number}
                  </span>
                  <div className="flex flex-col gap-0.5">
                    <span className="text-white font-medium">{step.action}</span>
                    <span className="text-slate-400 text-[11px] italic">Reason: {step.reason}</span>
                  </div>
                </div>
              ))}
            </div>
            <div className="text-xs text-emerald-300 font-mono pt-1">
              <strong>Outcome:</strong> {workedExample.result} — {workedExample.why_this_works}
            </div>
          </div>
        ) : null}
      </div>

      {/* ========================================================================= */}
      {/* 3. THE PYTHON PSEUDOCODE / IMPLEMENTATION (Default: Python) */}
      {/* ========================================================================= */}
      {pythonCode && (
        <div className="rounded-2xl bg-[#0E1526]/95 border border-[#1F2F4A] p-6 sm:p-7 shadow-xl flex flex-col gap-4 text-[#DFE8F2]">
          <div className="flex items-center justify-between border-b border-[#1F2F4A] pb-3">
            <div className="flex items-center gap-2 text-sm font-mono font-bold text-white uppercase tracking-wider">
              <span className="flex items-center justify-center w-6 h-6 rounded-md bg-[#F59E0B]/20 text-[#F59E0B] text-xs font-black">
                3
              </span>
              <span>Python Pseudocode & Implementation</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-mono text-[#F59E0B] px-2 py-0.5 rounded bg-[#F59E0B]/10 border border-[#F59E0B]/20">
                Python 3 (Default)
              </span>
              <button
                onClick={handleCopyCode}
                className="px-3 py-1 rounded bg-[#141F36] hover:bg-[#1A2844] border border-[#1F2F4A] text-xs font-mono text-slate-200 hover:text-white transition-colors flex items-center gap-1.5"
                title="Copy Python Code"
              >
                <span className="material-symbols-outlined text-xs">
                  {copiedCode ? 'check' : 'content_copy'}
                </span>
                <span>{copiedCode ? 'Copied!' : 'Copy Code'}</span>
              </button>
            </div>
          </div>

          <div className="rounded-xl bg-[#06080F] border border-[#1F2F4A] p-4 font-mono text-xs overflow-x-auto relative group">
            <pre className="text-sky-200 whitespace-pre leading-relaxed">
              <code>{pythonCode}</code>
            </pre>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* MISCONCEPTION CONTRAST (If diagnosed or detected) */}
      {/* ========================================================================= */}
      {misconceptionContrast && (
        <div className="flex flex-col gap-3 p-5 rounded-xl bg-amber-950/20 border border-amber-500/30">
          <div className="flex items-center gap-2 text-amber-400 font-mono text-xs uppercase font-bold tracking-wider">
            <span className="material-symbols-outlined text-sm">warning</span>
            Conceptual Distinction & Common Pitfalls
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
            <div className="p-3 rounded-lg bg-[#06080F] border border-emerald-500/30 flex flex-col gap-1">
              <span className="text-emerald-400 font-mono font-semibold">✓ Correct Mental Model</span>
              <p className="text-[#DFE8F2]">{misconceptionContrast.correct_model}</p>
            </div>
            <div className="p-3 rounded-lg bg-[#06080F] border border-rose-500/30 flex flex-col gap-1">
              <span className="text-rose-400 font-mono font-semibold">✕ Common Misconception</span>
              <p className="text-[#DFE8F2]">{misconceptionContrast.mistaken_model}</p>
            </div>
          </div>
          <p className="text-xs text-amber-200/90 font-mono">
            <strong>Key Distinction:</strong> {misconceptionContrast.key_distinction}
          </p>
        </div>
      )}

      {/* ========================================================================= */}
      {/* ACTIVE RECALL / SELF EXPLANATION PROMPT */}
      {/* ========================================================================= */}
      {selfExplanationPrompt && (
        <div className="flex flex-col gap-3 p-5 rounded-xl bg-[#081224] border border-teal-500/30">
          <span className="text-xs font-mono font-semibold uppercase tracking-wider text-teal-300 flex items-center gap-1.5">
            <span className="material-symbols-outlined text-sm">draw</span>
            Active Self-Explanation Check
          </span>
          <p className="text-xs text-[#DFE8F2] leading-relaxed">{selfExplanationPrompt}</p>
          {!reflectionSubmitted ? (
            <div className="flex flex-col gap-2">
              <textarea
                value={userReflection}
                onChange={(e) => setUserReflection(e.target.value)}
                placeholder="Type your brief explanation here to calibrate your mental model before starting exercises..."
                rows={2}
                className="w-full rounded-lg bg-[#06080F] border border-[#1F2F4A] p-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-teal-400 font-sans"
              />
              <button
                onClick={() => userReflection.trim() && setReflectionSubmitted(true)}
                disabled={!userReflection.trim()}
                className="self-end px-3.5 py-1.5 rounded-lg bg-teal-600/80 hover:bg-teal-500 text-white font-mono text-xs disabled:opacity-40 transition-colors"
              >
                Verify Explanation
              </button>
            </div>
          ) : (
            <div className="p-3 rounded-lg bg-teal-950/40 border border-teal-500/40 text-xs text-teal-200 flex items-center gap-2">
              <span className="material-symbols-outlined text-sm text-teal-400">check_circle</span>
              <span>Active recall recorded! Your conceptual grasp is reinforced for the upcoming practice.</span>
            </div>
          )}
        </div>
      )}

      {/* ========================================================================= */}
      {/* KEY TAKEAWAYS */}
      {/* ========================================================================= */}
      {keyTakeaways.length > 0 && (
        <div className="flex flex-col gap-2.5 p-5 rounded-xl bg-[#0A101D] border border-[#1F2F4A]">
          <span className="text-xs font-mono font-semibold uppercase tracking-wider text-[#10B981] flex items-center gap-1.5">
            <span className="material-symbols-outlined text-sm">checklist</span>
            Key Conceptual Takeaways
          </span>
          <ul className="flex flex-col gap-1.5 text-xs text-[#DFE8F2]">
            {keyTakeaways.map((takeaway, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-[#00D2FF] font-mono mt-0.5">•</span>
                <span>{takeaway}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* ========================================================================= */}
      {/* 5-LEVEL HINT LADDER PREVIEW */}
      {/* ========================================================================= */}
      {hintLadder.length > 0 && (
        <div className="flex flex-col gap-2.5 p-4 rounded-xl bg-[#06080F] border border-[#1F2F4A]">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono uppercase text-sky-400 flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm">lightbulb</span>
              Scaffolded Hint Ladder ({hintLadder.length} Levels Available)
            </span>
            <button
              onClick={() => setHintLevel(prev => (prev < hintLadder.length ? prev + 1 : 0))}
              className="text-[11px] font-mono text-sky-300 hover:text-white px-2.5 py-1 rounded bg-[#141F36] border border-[#1F2F4A]"
            >
              {hintLevel === 0 ? 'Preview Hint 1' : hintLevel < hintLadder.length ? `Reveal Hint ${hintLevel + 1}` : 'Collapse Hints'}
            </button>
          </div>
          {hintLevel > 0 && (
            <div className="flex flex-col gap-2 mt-2">
              {hintLadder.slice(0, hintLevel).map((h, idx) => (
                <div key={idx} className="p-2.5 rounded bg-[#0E1526] border border-[#1F2F4A] text-xs flex items-start gap-2">
                  <span className="px-1.5 py-0.5 rounded bg-sky-500/20 text-[#00D2FF] font-mono text-[10px]">
                    {h.label}
                  </span>
                  <span className="text-[#DFE8F2]">{h.text}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* ========================================================================= */}
      {/* RECOMMENDED RESOURCES */}
      {/* ========================================================================= */}
      {resourceSelection && resourceSelection.recommended_links && resourceSelection.recommended_links.length > 0 && (
        <div className="flex flex-col gap-2 pt-2 border-t border-[#1F2F4A]">
          <span className="text-xs font-mono text-[#8EA4B8] flex items-center gap-1.5 uppercase tracking-wider">
            <span className="material-symbols-outlined text-sm text-[#F59E0B]">library_books</span>
            Verified Course Resources
          </span>
          <div className="flex flex-wrap gap-2">
            {resourceSelection.recommended_links.map((link, idx) => {
              const title = typeof link === 'string' ? link : link.title || link.url || 'Resource Link';
              const url = typeof link === 'string' ? link : link.url || '#';
              return (
                <a
                  key={idx}
                  href={url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-3 py-1.5 rounded-lg bg-[#0A101D] border border-[#1F2F4A] hover:border-[#00D2FF] text-xs font-mono text-sky-300 hover:text-white transition-all flex items-center gap-1.5"
                >
                  <span className="material-symbols-outlined text-xs">open_in_new</span>
                  <span>{title}</span>
                </a>
              );
            })}
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* PRIMARY CTA: I'm Ready — Start Practice */}
      {/* ========================================================================= */}
      <div className="p-5 rounded-2xl bg-[#0B111E] border border-[#00D2FF]/30 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-2xl">
        <div className="flex flex-col">
          <span className="text-sm font-semibold text-white">Understood the concept?</span>
          <span className="text-xs text-[#8EA4B8]">
            Proceed to the adaptive practice task designed by the Exercise Agent.
          </span>
        </div>

        <button
          onClick={handleStartPractice}
          disabled={loading}
          className="w-full sm:w-auto px-7 py-3.5 rounded-xl bg-[#00D2FF] hover:bg-cyan-400 text-slate-950 font-mono font-bold text-sm transition-all shadow-[0_0_20px_rgba(0,210,255,0.4)] disabled:opacity-50 flex items-center justify-center gap-2 cursor-pointer"
        >
          {loading ? (
            <>
              <span className="material-symbols-outlined text-base animate-spin">sync</span>
              <span>Transitioning to Practice...</span>
            </>
          ) : (
            <>
              <span>I'm Ready — Start Practice</span>
              <span className="material-symbols-outlined text-base">arrow_forward</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
};
