"""
VISION Exercise Agent — Fully dynamic, open-domain adaptive assessment engine.
Zero hardcoded questions. Adapts exercise format (MCQ, Fill-in, Free Text, Coding)
to the concept, subject, learner level, learning goal, and state machine phase.
"""

from __future__ import annotations
from typing import Literal, Optional
from slice.state_manager import Exercise
from slice.llm_client import LLMClient


class ExerciseAgent:
    """
    Adaptive Assessment Engine.
    Generates targeted assessment exercises for ANY concept in ANY subject.
    Adapts exercise format based on workflow state:
      - initial_target: MCQ / Reasoning
      - prereq_recheck: Targeted fill-in or MCQ
      - target_retest: Applied problem or Coding exercise
      - tie_breaker: Single-step Exit Ticket
    """

    SYSTEM_PROMPT = """You are the VISION Exercise Agent — an expert assessment author.

Your job: generate ONE clear, targeted exercise to evaluate student understanding of a specific concept.

Question Formats:
- "mcq": 4 distinct options with exactly 1 correct answer.
- "fill_in_blank": Template string containing "___".
- "coding_problem": Programming problem with starter code, language, and 2+ test cases.
- "free_text": Short-answer conceptual reasoning question.

Rules:
- Adapt the format to the concept, subject, level, and learning goal.
- Make questions rigorous yet fair.
- Do NOT output answer keys or hidden secrets in question_text.

Respond with JSON only:
{
  "question_format": "mcq | fill_in_blank | coding_problem | free_text",
  "question_text": "<problem statement>",
  "mcq_options": ["Option A", "Option B", "Option C", "Option D"],
  "blank_template": "<sentence with ___ placeholder>",
  "code_starter": "<starter code template>",
  "language": "python | javascript | cpp | java",
  "test_cases": [
    {"input": "...", "expected_output": "...", "description": "..."}
  ],
  "expected_answer_hint": "<internal grading criteria note>"
}"""

    def __init__(self):
        self.llm = LLMClient()

    def generate_exercise(
        self,
        run_id: str,
        concept: str,
        exercise_type: Literal["prereq_recheck", "target_retest", "tie_breaker", "initial_target"],
        subject: str = "",
        context: str = "",
        learner_level: str = "intermediate",
        learning_goal: str = "understand",
        attempt_count: int = 0,
        curriculum_questions: Optional[list] = None
    ) -> Exercise:
        concept_clean = concept.replace("_", " ").title()

        # 1. Use pre-vetted curriculum questions generated by SupervisorAgent if available
        if curriculum_questions and len(curriculum_questions) > 0 and exercise_type in {"initial_target", "tie_breaker"}:
            q_idx = min(attempt_count, len(curriculum_questions) - 1)
            cq = curriculum_questions[q_idx]
            q_text = cq.get("question") or f"What is the key mechanism behind {concept_clean}?"
            q_opts = cq.get("options") or []
            q_fmt = cq.get("question_format") or ("mcq" if q_opts else "free_text")
            return Exercise(
                run_id=run_id,
                concept=concept,
                exercise_type=exercise_type,
                question_text=q_text,
                rubric_ref=f"dynamic:{subject}:{concept}",
                question_format=q_fmt,
                mcq_options=q_opts,
                expected_answer_hint=cq.get("explanation") or cq.get("correct_answer") or ""
            )

        if not self.llm.is_live:
            c_lower = concept.lower()
            if "linked_list" in concept or "linked list" in c_lower:
                return Exercise(
                    run_id=run_id,
                    concept=concept,
                    exercise_type=exercise_type,
                    question_format="mcq",
                    question_text=f"In a Singly Linked List, what is the time complexity of inserting a node at the head versus inserting at an arbitrary index k?",
                    rubric_ref=f"dynamic:{subject}:{concept}",
                    mcq_options=[
                        "O(1) at the head, O(k) at arbitrary index due to linear traversal",
                        "O(1) for both operations because pointers allow instant indexing",
                        "O(n) at the head, O(1) at arbitrary index",
                        "O(log n) using binary pointer search"
                    ],
                    expected_answer_hint="Inserting at head only requires redirecting next pointers (O(1)). Arbitrary index requires traversing k nodes from head (O(k))."
                )
            elif "stack" in concept or "stack" in c_lower:
                return Exercise(
                    run_id=run_id,
                    concept=concept,
                    exercise_type=exercise_type,
                    question_format="mcq",
                    question_text=f"Which sequence of operations on an empty Stack results in top element being 20?",
                    rubric_ref=f"dynamic:{subject}:{concept}",
                    mcq_options=[
                        "push(10) -> push(20)",
                        "push(20) -> push(10)",
                        "push(20) -> pop()",
                        "push(10) -> push(30) -> push(20) -> pop()"
                    ],
                    expected_answer_hint="push(10) followed by push(20) puts 20 at the top of the LIFO stack."
                )
            elif exercise_type == "tie_breaker":
                return Exercise(
                    run_id=run_id,
                    concept=concept,
                    exercise_type=exercise_type,
                    question_format="mcq",
                    question_text=f"Exit Ticket: Which foundational property best defines {concept_clean}?",
                    rubric_ref=f"dynamic:{subject}:{concept}",
                    mcq_options=[
                        f"Specific algorithmic invariant structuring memory and operational complexity",
                        f"Direct element placement without ordering constraints",
                        f"Unconditional program termination interrupt",
                        f"Arbitrary secondary reference assignment"
                    ]
                )
            elif exercise_type == "prereq_recheck":
                return Exercise(
                    run_id=run_id,
                    concept=concept,
                    exercise_type=exercise_type,
                    question_format="fill_in_blank",
                    question_text=f"Complete the core rule for {concept_clean}: Before processing higher-level operations, the system must first evaluate the ___ state.",
                    blank_template=f"Before processing higher-level operations, the system must first evaluate the ___ state.",
                    rubric_ref=f"dynamic:{subject}:{concept}"
                )
            else:
                return Exercise(
                    run_id=run_id,
                    concept=concept,
                    exercise_type=exercise_type,
                    question_format="mcq",
                    question_text=f"What is the primary architectural purpose of {concept_clean} in {subject or 'Computer Science'}?",
                    rubric_ref=f"dynamic:{subject}:{concept}",
                    mcq_options=[
                        f"Structures and organizes data to optimize access patterns and runtime/memory bounds",
                        f"Disables CPU instruction caching",
                        f"Bypasses memory allocation limits",
                        f"Forces immediate program exit"
                    ]
                )

        user_prompt = f"""Subject: {subject or 'Computer Science'}
Concept: {concept_clean}
Exercise Type: {exercise_type}
Learner Level: {learner_level}
Learning Goal: {learning_goal}
Attempt Count: {attempt_count}
Workflow Context: {context or 'None'}

Generate a technically rigorous CS assessment exercise (MCQ, Fill-in, Coding, or Free Text) specifically about {concept_clean}. Return JSON."""

        result = self.llm.chat_json(self.SYSTEM_PROMPT, user_prompt, max_tokens=768)

        q_format = result.get("question_format") or "mcq"
        question = result.get("question_text") or f"What is the key mechanism behind {concept_clean}?"
        mcq_opts = result.get("mcq_options") or []
        blank_tmpl = result.get("blank_template")
        starter = result.get("code_starter")
        lang = result.get("language") or "python"
        tests = result.get("test_cases") or []

        return Exercise(
            run_id=run_id,
            concept=concept,
            exercise_type=exercise_type,
            question_text=question,
            rubric_ref=f"dynamic:{subject}:{concept}",
            question_format=q_format,
            mcq_options=mcq_opts,
            blank_template=blank_tmpl,
            code_starter=starter,
            language=lang,
            test_cases=tests
        )
